Optimized installation Script
yogeshojha/rengine pull request #1007
Opened 2023-10-20 14:06 UTC by 4NK1T

2023-10-20 21:21 UTC, AnonymousWP commented
Could you specify in your PR what exactly has been changed? That's easier when I'm going through the code.

2023-10-24 08:40 UTC, 4NK1T commented
Function for Logging (3-7)
Root priveleges check using the "id -u" check more efficiently (9-15)
Output messages are grouped into sections using the log function (19-48)
Dependencies (CURL, Docker, docker-compose, make) are checked and installed more efficiently in a single section (50-70)
Docker status is checked using "docker info" with more detailed error messages.
Installation success and failure are checked with conditional statements and better error handling.

2023-10-24 09:19 UTC, AnonymousWP commented
Sounds great. Have you tested this thoroughly too? e.g. without having installed `make`, Docker Compose, Docker, etc? In short: does everything work?

2023-10-25 17:34 UTC, 4NK1T commented
Yes tried and tested twice.

2023-10-25 21:44 UTC, AnonymousWP approved these changes

2023-10-25 21:47 UTC, AnonymousWP requested changes
It currently conflicts with https://github.com/yogeshojha/rengine/pull/973. Could you actually merge/integrate that change into your branch?

2024-07-19 05:51 UTC, closed without merging