Feat/multiple targets in org bulk upload via csv
yogeshojha/rengine pull request #1109
Opened 2023-12-06 10:40 UTC by SeanOverton

- addresses issue #604 by allowing optional extra parameter ('organisation') in bulk upload of targets via csv file

2023-12-06 11:49 UTC, AnonymousWP requested changes
As we're using US English in reNgine, we'd like to keep this consistent. Also, thank you for this PR!

2023-12-06 11:49 UTC, AnonymousWP commented on web/targetApp/templates/target/add.html
> +                By default all domains imported from txt will have no description and no organisation. If you choose to import multiple domains with description and/or organisation, csv import is rec
```suggestion
                By default all domains imported from txt will have no description and no organization. If you choose to import multiple domains with description and/or organization, csv import is recommended.
```

2023-12-06 11:49 UTC, AnonymousWP commented on web/targetApp/templates/target/add.html
> +                Your csv file must be in the format of <strong>domain, description, organisation</strong> separated by a new line.
```suggestion
                Your csv file must be in the format of <strong>domain, description, organization</strong> separated by a new line.
```

2023-12-06 12:07 UTC, SeanOverton commented
> As we're using US English in reNgine, we'd like to keep this consistent. Also, thank you for this PR!

Yeh! This spelling caught me out a few times 😆 thanks for catching this

2023-12-06 17:34 UTC, psyray approved these changes

2023-12-18 01:30 UTC, yogeshojha approved these changes

2023-12-18 01:30 UTC, merged