fix some typos / mistakes in README
yogeshojha/rengine pull request #1132
Opened 2023-12-12 17:17 UTC by jxdv

^title

2023-12-13 12:31 UTC, AnonymousWP requested changes

2023-12-13 12:31 UTC, AnonymousWP commented on README.md
> +reNgine 2.0-Jasper would not have been possible without [@ocervell](https://github.com/ocervell) valuable contributions. [@ocervell](https://github.com/ocervell) did the majority of the refactoring i
```suggestion
reNgine 2.0-Jasper would not have been possible without [@ocervell](https://github.com/ocervell) valuable contributions. [@ocervell](https://github.com/ocervell) did the majority of the refactoring (if not all) and also added a ton of features. Together, we wish to shape the future of web application reconnaissance, and it's developers like [@ocervell](https://github.com/ocervell) and a [ton of other developers and hackers from our community](https://github.com/yogeshojha/rengine/graphs/contributors) who inspire and drive us forward.
```

2023-12-16 18:39 UTC, AnonymousWP approved these changes

2023-12-16 18:39 UTC, AnonymousWP commented on README.md
> +* Patience: Please note that I am currently the only maintainer in reNgine, and it will take some time to validate your report. I ask for your patience during this process.
```suggestion
```

Can be removed as we're with 3 maintainers now.

2023-12-16 18:39 UTC, AnonymousWP requested changes
Oops, I meant to request, not approve.

2023-12-16 19:36 UTC, AnonymousWP approved these changes

2023-12-18 01:38 UTC, yogeshojha commented
@jxdv please fix merge conflict.

2023-12-18 10:14 UTC, jxdv commented
> @jxdv please fix merge conflict.

Done.

2023-12-18 20:40 UTC, psyray approved these changes

2023-12-19 12:23 UTC, merged