Update issue templates
yogeshojha/rengine pull request #901
Opened 2023-05-17 11:13 UTC by itasahobby

In an attempt to prevent issues that are not relevant (e.g https://github.com/yogeshojha/rengine/issues/893) updated the issue templates to use new [github issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).

2023-05-17 12:11 UTC, AnonymousWP requested changes
I'd say there's more required, such as more environments (e.g. Docker Engine version, Docker Compose version, etc.). I'd recommend taking a look at the development stack and see what software is required.

2023-05-17 13:53 UTC, itasahobby commented
Sure @AnonymousWP, added some more fields that may be of interest.

2023-05-19 07:36 UTC, AnonymousWP requested changes
Should be fine after these suggestions.

2023-05-19 07:36 UTC, AnonymousWP commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +        - browser
```suggestion
        - reNgine: 
        - OS: 
        - Python: 
        - Docker Engine: 
        - Docker Compose: 
        - Browser: 
```

2023-05-19 07:36 UTC, AnonymousWP commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +title: "<title>"
```suggestion
title: "feat: <title>"
```

2023-05-19 07:36 UTC, AnonymousWP commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +title: "[BUG] <title>"
```suggestion
title: "bug: <title>"
```

2023-05-19 07:50 UTC, itasahobby commented
Alright

2023-07-20 13:30 UTC, itasahobby commented
Any updates on this? @AnonymousWP

2023-07-29 14:00 UTC, AnonymousWP commented
> Any updates on this? @AnonymousWP

Yogesh needs to merge this, but he'll likely do that after he released reNgine 2.0.

2023-10-02 09:00 UTC, yogeshojha approved these changes

2023-10-02 09:00 UTC, merged

2023-10-02 09:01 UTC, yogeshojha commented
Excellent guys :heart: